name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          python -m pip install --upgrade pip setuptools wheel build
          python -m pip install pytest pytest-asyncio pytest-postgresql pylint
          python -m build
          for f in dist/*.whl; do pip install $f; done

      - name: Test with pytest
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
        run: |
          python3 -m pytest ./tests